Feature/calcular salario
GuillaumeFalourd/java-exercices pull request #37
Opened 2021-10-30 17:25 UTC by dorayenCarrasquel

### Descrição

2021-11-03 12:13 UTC, GuillaumeFalourd requested changes
Obrigado pela contribuição @dorayenCarrasquel 👏🏼  
Só fiz uma observação em relação a padronização do projeto. A implementação em se está ok 👍🏼

2021-11-03 12:13 UTC, GuillaumeFalourd commented on 0-BASICO/1-estrutura-sequencial.md
> +[Resolução do Exercicio](https://github.com/dorayenCarrasquel/java-exercices.git)
Já que cabe tudo num método só, o que acharia de deixar tudo o código aqui (igual outras resoluções presentes no arquivo) no lugar de redirecionar para uma outra classe?

2021-11-04 22:01 UTC, dorayenCarrasquel commented
Implantada sugestão de padronização.

2021-11-04 22:02 UTC, dorayenCarrasquel commented on 0-BASICO/1-estrutura-sequencial.md
> +[Resolução do Exercicio](https://github.com/dorayenCarrasquel/java-exercices.git)
Resolução Implementada

2021-11-05 15:14 UTC, GuillaumeFalourd approved these changes
Beleza. Obrigado por sua participação @dorayenCarrasquel 🚀

2021-11-05 15:14 UTC, merged